# Generated by Django 5.2.10 on 2026-02-04 03:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Roznamcha', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Smart Khata & Hisab System', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Branding',
                'verbose_name_plural': 'App Branding',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('is_cash_or_bank', models.BooleanField(default=False)),
                ('allow_for_payments', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('owner', models.OneToOneField(help_text='Company owner user (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_credits', to='core.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_debits', to='core.account')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('opening_balance_is_debit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('IN', 'Receipt (money in)'), ('OUT', 'Payment (money out)')], default='IN', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('related_model', models.CharField(blank=True, max_length=50)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_adjustment', models.BooleanField(default=False)),
                ('adjustment_side', models.CharField(blank=True, choices=[('DR', 'Dr'), ('CR', 'Cr')], help_text='For adjustments only: DR or CR', max_length=2)),
                ('account', models.ForeignKey(blank=True, help_text='Cash or bank account used for this transaction.', limit_choices_to={'is_cash_or_bank': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(blank=True, help_text='Customer / Supplier / other counterparty.', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code like UREA50, DAP50, WHEAT50, etc.', max_length=30)),
                ('name', models.CharField(help_text='Full product name shown on invoices.', max_length=150)),
                ('unit', models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10)),
                ('packing_type', models.CharField(choices=[('NONE', 'No packing / loose'), ('CARTON', 'Carton'), ('BAG', 'Bag'), ('CONTAINER', 'Container'), ('BUNDLE', 'Bundle')], default='NONE', max_length=20)),
                ('pieces_per_pack', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('purchase_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Supplier bill number (optional).', max_length=50)),
                ('invoice_date', models.DateField()),
                ('date_received', models.DateField(blank=True, help_text='Optional: physical goods received date.', null=True)),
                ('freight_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('posted', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('CREDIT', 'Credit (we will pay later)'), ('FULL', 'Full payment (cash/bank)'), ('PARTIAL', 'Partial payment')], default='CREDIT', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually paid at time of purchase (0 for pure credit).', max_digits=14)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(blank=True, help_text='Cash/Bank account if payment made at time of purchase.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_payment_invoices', to='core.account')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10)),
                ('quantity_units', models.DecimalField(decimal_places=3, help_text='Quantity in base units (bag/kg/litre/unit).', max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Purchase price per unit for this invoice.', max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Per-line discount (flat amount, not %).', max_digits=14)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoice_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='core.product')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('posted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to=settings.AUTH_USER_MODEL)),
                ('reference_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.purchaseinvoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='core.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10)),
                ('quantity_units', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='core.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchasereturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('invoice_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('posted', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('CREDIT', 'Credit (customer will pay later)'), ('FULL', 'Full payment (cash/bank)'), ('PARTIAL', 'Partial payment')], default='CREDIT', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='core.party')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payment_invoices', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10)),
                ('quantity_units', models.DecimalField(decimal_places=3, help_text='Quantity in base units (bag/kg/litre/unit).', max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Sale price per unit for this invoice.', max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Per-line discount (flat amount, not %).', max_digits=14)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='core.product')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('posted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='core.party')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to=settings.AUTH_USER_MODEL)),
                ('reference_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='core.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_type', models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10)),
                ('quantity_units', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='sales_return_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_items', to='core.product')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.salesreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('DOWN', 'Decrease (damage/expired/loss)'), ('UP', 'Increase (correction/add stock)')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('OWNER', 'Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Only for STAFF: link to the company owner user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='unique_account_code_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('owner', 'related_model', 'related_id'), name='uniq_journal_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('owner', 'name', 'party_type'), name='unique_party_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('owner', 'related_model', 'related_id'), name='unique_payment_per_document_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='unique_product_code_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(fields=('owner', 'invoice_number'), name='unique_purchase_invoice_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('owner', 'invoice_number'), name='unique_sales_invoice_per_owner'),
        ),
    ]
