# Generated by Django 5.2.10 on 2026-02-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, help_text='When subscription expires (OWNER only).', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='TRIAL', help_text='Only meaningful for OWNER accounts. STAFF inherits OWNER subscription.', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text='When the trial started (set on first use / signup).', null=True),
        ),
    ]
