# Generated by Django 5.2.10 on 2026-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backfill_owner_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Tenant subdomain slug (e.g. amir, abc-traders).', null=True, unique=True),
        ),
    ]
