# Generated by Django 5.2.10 on 2026-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
