# Generated by Django 5.2.10 on 2026-02-06 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_companyprofile_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'code'], name='core_accoun_owner_i_200771_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['owner', 'account_type'], name='core_accoun_owner_i_14952f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['slug'], name='core_compan_slug_2b04c2_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', 'date', 'id'], name='core_journa_owner_i_be931a_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', 'related_model', 'related_id'], name='core_journa_owner_i_f33de6_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['owner', 'party_type', 'name'], name='core_party_owner_i_611da9_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['owner', 'is_active'], name='core_party_owner_i_ae0c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['owner', 'date', 'id'], name='core_paymen_owner_i_611c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['owner', 'posted'], name='core_paymen_owner_i_fa8f68_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['owner', 'related_model', 'related_id'], name='core_paymen_owner_i_daf919_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'code'], name='core_produc_owner_i_0bc880_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'is_active'], name='core_produc_owner_i_db5528_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['owner', 'invoice_date', 'id'], name='core_purcha_owner_i_03b776_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['owner', 'posted'], name='core_purcha_owner_i_d79371_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['owner', 'invoice_number'], name='core_purcha_owner_i_7164fd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['owner', 'purchase_invoice'], name='core_purcha_owner_i_8838db_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoiceitem',
            index=models.Index(fields=['owner', 'product'], name='core_purcha_owner_i_1c4387_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['owner', 'return_date', 'id'], name='core_purcha_owner_i_348f16_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['owner', 'posted'], name='core_purcha_owner_i_feac80_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['owner', 'purchase_return'], name='core_purcha_owner_i_8c93e0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnitem',
            index=models.Index(fields=['owner', 'product'], name='core_purcha_owner_i_b718ef_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['owner', 'invoice_date', 'id'], name='core_salesi_owner_i_e696bc_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['owner', 'posted'], name='core_salesi_owner_i_61ba7b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['owner', 'invoice_number'], name='core_salesi_owner_i_7fcf97_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['owner', 'sales_invoice'], name='core_salesi_owner_i_a1c8be_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoiceitem',
            index=models.Index(fields=['owner', 'product'], name='core_salesi_owner_i_9bd317_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['owner', 'return_date', 'id'], name='core_salesr_owner_i_13f6a3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['owner', 'posted'], name='core_salesr_owner_i_9988b5_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['owner', 'sales_return'], name='core_salesr_owner_i_91c86a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturnitem',
            index=models.Index(fields=['owner', 'product'], name='core_salesr_owner_i_055f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['owner', 'date', 'id'], name='core_stocka_owner_i_f1bc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['owner', 'posted'], name='core_stocka_owner_i_673393_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['owner', 'product'], name='core_stocka_owner_i_08c346_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='core_userpr_role_ce56eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='core_userpr_is_acti_5e1476_idx'),
        ),
        
    ]
