# Generated by Django 5.2.10 on 2026-02-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_account_core_accoun_owner_i_200771_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
