# Generated by Django 5.2.10 on 2026-02-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='owner_ntn',
            field=models.CharField(blank=True, help_text='Optional NTN for owner (used in Tax Pack documents).', max_length=25, null=True),
        ),
    ]
