# Generated by Django 5.2.10 on 2026-02-15 04:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_owner_ntn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('default_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage value. Example: 18.00 for 18%.', max_digits=6)),
                ('applies_to', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('BOTH', 'Both')], default='SALE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
