# Generated by Django 5.2.10 on 2026-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_taxtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxType',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='owner_ntn',
        ),
    ]
