# Generated by Django 5.2.10 on 2026-02-20 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_taxtype_remove_userprofile_owner_ntn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('expense_head', models.ForeignKey(help_text='Expense account head (e.g., Wages, Food, Fuel).', limit_choices_to={'account_type': 'EXPENSE'}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_heads_used', to='core.account')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='daily_expenses', to=settings.AUTH_USER_MODEL)),
                ('paid_from', models.ForeignKey(help_text='Cash/Bank account used to pay the expense.', limit_choices_to={'allow_for_payments': True, 'is_cash_or_bank': True}, on_delete=django.db.models.deletion.PROTECT, related_name='expense_paid_from', to='core.account')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'date', 'id'], name='core_dailye_owner_i_239bca_idx'), models.Index(fields=['owner', 'posted'], name='core_dailye_owner_i_49036c_idx'), models.Index(fields=['owner', 'expense_head'], name='core_dailye_owner_i_cd0401_idx'), models.Index(fields=['owner', 'paid_from'], name='core_dailye_owner_i_3fe2c9_idx')],
            },
        ),
    ]
