# Generated by Django 5.2.10 on 2026-02-20 11:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dailyexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('posted', models.BooleanField(default=False)),
                ('from_account', models.ForeignKey(limit_choices_to={'allow_for_payments': True, 'is_cash_or_bank': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cashbank_transfers_out', to='core.account')),
                ('owner', models.ForeignKey(help_text='Company owner (this user is the company).', on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(limit_choices_to={'allow_for_payments': True, 'is_cash_or_bank': True}, on_delete=django.db.models.deletion.PROTECT, related_name='cashbank_transfers_in', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
