# Generated by Django 5.2.10 on 2026-02-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cashbanktransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_type',
            field=models.CharField(choices=[('NONE', 'No packing / loose'), ('CARTON', 'Carton'), ('BAG', 'Bag'), ('CONTAINER', 'Container'), ('BUNDLE', 'Bundle'), ('BOX', 'Box'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('SACHET', 'Sachet'), ('PACKET', 'Packet / Pack')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Tonne'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('M', 'Meter'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='unit_type',
            field=models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Tonne'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('M', 'Meter'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_type',
            field=models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Tonne'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('M', 'Meter'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='unit_type',
            field=models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Tonne'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('M', 'Meter'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='unit_type',
            field=models.CharField(choices=[('BAG', 'Bag'), ('KG', 'Kilogram'), ('G', 'Gram'), ('TON', 'Tonne'), ('LITRE', 'Litre'), ('ML', 'Millilitre'), ('M', 'Meter'), ('ROLL', 'Roll'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen'), ('UNIT', 'Unit / Piece')], default='BAG', max_length=10),
        ),
        migrations.CreateModel(
            name='OwnerSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'key')},
            },
        ),
    ]
