# Generated by Django 5.2.10 on 2026-02-27 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_packing_type_alter_product_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(max_length=20)),
                ('duration_days', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('provider', models.CharField(default='JAZZCASH', max_length=20)),
                ('merchant_ref', models.CharField(db_index=True, max_length=80, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='INITIATED', max_length=12)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('return_payload', models.JSONField(blank=True, null=True)),
                ('ipn_payload', models.JSONField(blank=True, null=True)),
                ('hash_ok', models.BooleanField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('return_received_at', models.DateTimeField(blank=True, null=True)),
                ('ipn_received_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='core_subscr_owner_i_931599_idx'), models.Index(fields=['provider', 'status'], name='core_subscr_provide_d2ae10_idx'), models.Index(fields=['created_at'], name='core_subscr_created_f794a4_idx')],
            },
        ),
    ]
