# Generated by Django 5.2.10 on 2026-03-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_subscriptiontransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='core.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
            ],
            options={
                'indexes': [models.Index(fields=['journal_entry', 'account'], name='core_journa_journal_bc5549_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0)), name='journal_line_debit_gte_0'), models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='journal_line_credit_gte_0'), models.CheckConstraint(condition=models.Q(('debit__gt', 0), ('credit__gt', 0), _negated=True), name='journal_line_not_both_debit_credit')],
            },
        ),
    ]
