# Generated by Django 5.2.10 on 2026-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subscriptiontransaction_hardening_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='business_setup_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
