# Generated by Django 5.2.10 on 2026-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_journalentryline'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='accounting_cutover_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='accounting_mode',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('v2', 'Accounting V2')], default='legacy', max_length=20),
        ),
    ]
