import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
"""
Django settings for agri_business project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""


# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    # safe default for local only (never production)
    SECRET_KEY = "dev-only-change-me"

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
# ✅ Hosts
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".localhost",
    ".lvh.me",
    "roznamcha.app",
    "www.roznamcha.app",
    ".roznamcha.app",
    ".onrender.com",
]
# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Tenant resolution for subdomain multi-tenant
    "core.middleware.TenantMiddleware",
]

ROOT_URLCONF = "agri_business.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # keep empty unless you add project-level templates folder
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.company_profile",
                "core.context_processors.app_branding",
            ],
        },
    },
]

WSGI_APPLICATION = "agri_business.wsgi.application"

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Render provides DATABASE_URL for Postgres
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }
else:
    # Local fallback (sqlite)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"

# ✅ Pakistan Standard Time
TIME_ZONE = "Asia/Karachi"

USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

WHITENOISE_MIMETYPES = {
    ".webmanifest": "application/manifest+json",
}
# Media (uploads like company logo)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# Multi-tenant domain config
# =========================

if DEBUG:
    SAAS_BASE_DOMAIN = "lvh.me"
    PUBLIC_BASE_DOMAIN = "lvh.me:8000"
    SESSION_COOKIE_DOMAIN = ".lvh.me"
    CSRF_COOKIE_DOMAIN = ".lvh.me"
    CSRF_TRUSTED_ORIGINS = [
        "http://lvh.me:8000",
        "http://alpha.lvh.me:8000",
        "http://beta.lvh.me:8000",
        "https://roznamcha.app",
        "https://www.roznamcha.app",
    ]
else:
    SAAS_BASE_DOMAIN = "roznamcha.app"
    PUBLIC_BASE_DOMAIN = "www.roznamcha.app"
    SESSION_COOKIE_DOMAIN = ".roznamcha.app"
    CSRF_COOKIE_DOMAIN = ".roznamcha.app"
    CSRF_TRUSTED_ORIGINS = [
        "https://roznamcha.app",
        "https://www.roznamcha.app",
        "https://roznamcha-web.onrender.com",
    ]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Auth redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "landing"